### ISSUE TITLE
[FIX] 라이벌 기반 문제 추천 모델 실행 시 "No CUDA extension has been built, can't train on GPU"

### ISSUE THREAD

**Issue by Glanceyes** [boostcampaitech3/final-project-level3-recsys-14#15]
### 😎 Responsibility

@sun1187, @seo-h2, @Glanceyes

### 💡Issue

AI Stages에서 제공한 서버(V100)에서 GCP VM 인스턴스(Tesla T4)로 이전한 이후 Implicit 라이브러리를 사용하는 라이벌 기반 문제 추천 모델(BPR, MF, Item-based)을 실행할 때"No CUDA extension has been built, can't train on GPU" Error가 뜨면서 정상적으로 학습이 되지 않는 현상이 발생합니다.

### ⌨️ Code

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.6/dist-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.6/dist-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.6/dist-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/usr/local/lib/python3.6/dist-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/recognizer14/airflow/dags/py_module_models_cmf_out.py", line 172, in rec_rival_pb_mf
    output = main_mf_als(db=db)
  File "/home/recognizer14/airflow/dags/module_models/rec_rival_pb/mf_als_problem.py", line 61, in main_mf_als
    als_model = ALS(factors=7, regularization=0.01, iterations = 50, random_state=seed, use_gpu=use_gpu_value)
  File "/home/recognizer14/.local/lib/python3.6/site-packages/implicit/als.py", line 62, in AlternatingLeastSquares
    random_state=random_state,
  File "/home/recognizer14/.local/lib/python3.6/site-packages/implicit/gpu/als.py", line 55, in __init__
    raise ValueError("No CUDA extension has been built, can't train on GPU.")
```

### 🔗 Reference

https://github.com/benfred/implicit/issues/332

### 🧭 To Do

- [x] cuda와 cudnn 재설치
- [x] 임시로 라이벌 기반 문제 추천 모델만 CPU로 학습하기

**Comment by Glanceyes** [comment]
CUDA 드라이버와 라이브러리, cudnn 재설치 시 같은 문제가 발생합니다.
의문인 건 GPU를 사용하는 다른 딥 러닝 모델은 정상적으로 실행됩니다.

**Comment by Glanceyes** [comment]
실제 GCP 배포 코드에서만 라이벌 문제 추천에 관해 GPU 사용 해제했습니다.
